version: '1.0'
stages:
  - prepare
  - test
  - integration
  - build
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'mstane/poc'
    revision: develop
    git: github
  MyUnitTests:
    title: Compile/Unit test
    stage: test
    image: 'adoptopenjdk/maven-openjdk11'
    working_directory: ./loggingpoc
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository package
  Integration:
    title: Integration test
    stage: integration
    image: 'adoptopenjdk/maven-openjdk11'
    working_directory: ./loggingpoc
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository verify
  MyAppDockerImage:
    title: Building Docker Image
    type: build
    stage: build
    image_name: mstane/loggingpoc
    working_directory: ./loggingpoc/target
    dockerfile: ../Dockerfile
    tag: 'non-multi-stage'


